name: Build ArchLinuxARM for Orange Pi 5 with vendor kernel
on:
  workflow_call:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Prepare deps
        run: |
          sudo apt update
          sudo apt install \
            libarchive-tools \
            qemu-user-static \
            systemd-container
      - name: Restore cached sources
        id: cache-restore-src
        uses: actions/cache/restore@v3
        with:
          path: src.tar
          key: ${{ runner.os }}-src
          restore-keys: ${{ runner.os }}-src
      - name: Extract cached sources
        if: steps.cache-restore-src.cache-hit == 'true'
        run: tar -xf src.tar
      - name: Cross build
        run: ./cross_nobuild.sh
      - name: Pack sources
        run: |
          tar -cf src.tar cross_nobuild/src
      - name: Save sources
        uses: actions/cache/save@v3
        with:
          path: src.tar
          key: ${{ runner.os }}-packages-${{ hashFiles('src.tar') }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          path: cross_nobuild/out/latest/*
          if-no-files-found: error
      
